####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

from router import Router


class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        self.infinity = 16
        self.links = {}
        self.neighbor_ports = {}
        self.dv = {self.addr: 0}
        self.forwarding_table = {}
        self.neighbor_dvs = {}

    def handle_packet(self, port, packet):
         """Process incoming packet."""
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            if packet.dst_addr in self.forwarding_table:
                out_port = self.forwarding_table[packet.dst_addr]   
                self.send(out_port, packet)
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            neighbor = packet.src_addr
            received_dv = json.loads(packet.content)
            
            if self.neighbor_dvs.get(neighbor) != received_dv:
                self.neighbor_dvs[neighbor] = received_dv
                changed = self.recompute_dv()
                if changed:
                    self.send_dv()
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        self.links[port] = (endpoint, cost)
        self.neighbor_ports[endpoint] = port 
        changed = False
        if endpoint not in self.dv or cost < self.dv[endpoint]:
        #   update the distance vector of this router
         self.dv[endpoint] = cost
        #   update the forwarding table
        self.forwarding_table[endpoint] = port
        #   broadcast the distance vector of this router to neighbors
        content = json.dumps(self.dv)
        for p in self.links:
            pkt = Packet(Packet.ROUTING, self.addr, None, content)
            self.send(p, pkt)
        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        import json
        from packet import Packet
        if port not in self.links:
            return
        endpoint, cost = self.links[port]
        del self.links[port]
        if endpoint in self.neighbor_ports:
            del self.neighbor_ports[endpoint]
        
        changed = False    
        #   update the distance vector of this router
        if endpoint in self.dv:
            self.dv[endpoint] = self.infinity
            changed = True
        affected = []
        for dest in self.forwarding_table:
            if self.forwarding_table[dest] == port:
                affected.append(dest)
        for dest in affected:
            self.dv[dest] = self.infinity
            changed = True              
        #   update the forwarding table
        for dest in affected:
            if dest in self.forwarding_table:
                del self.forwarding_table[dest]
        if endpoint in self.forwarding_table[endpoint]        
        #   broadcast the distance vector of this router to neighbors
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr})"
